log:
  level: info
  file: "/tmp/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"
include: []
plugins:

 ## > GeoSite 规则
  - tag: local_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/var/mosdns/geosite_tld-cn.txt"
        - "/var/mosdns/geosite_category-games@cn.txt"
        - "/var/mosdns/geosite_apple-cn.txt"
        - "/var/mosdns/geosite_icloud.txt"
  - tag: remote_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

 ## > OpenWrt luci 网页规则
  # 灰名单 加入的域名始终使用 “国外解析” 进行解析
  - tag: greylist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"
  # DDNS域名 加入的域名始终使用 “本地 DNS” 进行解析，并且修改 TTL 为 5 秒，解析结果不进行缓存
  - tag: ddnslist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/ddnslist.txt"
  # 自定义 Hosts 重写
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

  ## > 缓存设置
  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  ## > 转发和解析设置
  # 转发到国内DNS服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: tls://223.5.5.5:853
        - addr: tls://1.12.12.12:853
          enable_pipeline: true

  # 转发到openclash
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: 127.0.0.1:7874

  ## > 解析判断逻辑
  # 查询是否为 国内域名
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: "qname $local_domain"
        exec: $forward_local

  # 查询是否为 国外域名
  - tag: query_is_global_domain
    type: sequence
    args:
      - matches: "qname $remote_domain"
        exec: $forward_remote

  # 查询是否为 DDNS 域名
  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: "qname $ddnslist"
        exec: $forward_local

  # 查询是否为 灰名单
  - tag: query_is_greylist_domain
    type: sequence
    args:
      - exec: prefer_ipv4
      - matches: "qname $greylist"
        exec: $forward_remote


  # 有响应则修改 TTL 
  - tag: has_resp
    type: sequence
    args:
      - exec: ttl 5-5
      - matches: "qname $local_domain"
        exec: ttl 600-3600
      - matches: has_resp
        exec: accept


  ## > 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp
      - exec: $query_is_ddns_domain
      - exec: jump has_resp
      - matches:
        - "qname $local_domain"
        exec: $lazy_cache
      - exec: $query_is_greylist_domain
      - exec: jump has_resp
      - exec: $query_is_local_domain
      - exec: jump has_resp
      - exec: $query_is_global_domain
      - exec: jump has_resp
      - exec: $forward_remote
      - exec: ttl 5-5

  # 启动 udp 服务器
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"
  # 启动 tcp 服务器。
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
