log:
  level: info
  file: "/tmp/mosdns.log"

  ## API 入口设置
api:
  http: "0.0.0.0:9091"
include: []
plugins:

  ## > GeoSite 规则
  - tag: local_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/var/mosdns/geosite_tld-cn.txt"
        - "/var/mosdns/geosite_category-games@cn.txt"
        - "/var/mosdns/geosite_apple-cn.txt"
        - "/var/mosdns/geosite_icloud.txt"
  ## > cloudflare_ip
  - tag: cloudflare_ip
    type: ip_set
    args:
      ips:
        - "1.1.1.0/24"
        - "1.0.0.0/24"
        - "162.158.0.0/15"
        - "104.16.0.0/12"
        - "172.64.0.0/13"
        - "2606:4700::/32"

  ## > 缓存设置
  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  ## > 转发和解析设置
  # 转发到国内DNS服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: tls://223.5.5.5:853
        - addr: tls://1.12.12.12:853
          enable_pipeline: true

  # 转发到OpenClash
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: 192.168.10.2:7874

  ## > 解析判断逻辑
  # 接受响应并修改ttl
  - tag: accept_resp
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept
      
  # 优选cloudflare_ip
  - tag: response_cloudflare_ip
    type: sequence
    args:
      - matches: "resp_ip $cloudflare_ip"
        exec: black_hole 104.20.19.35 2a06:98c1:3121:2080:6267:8f60:7135:c1f7 # 请修改为自选 IP
      - exec: $accept_resp    
        
  # 查询是否为 国内域名
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: "qname $local_domain"
        exec: $forward_local
        
  # 有响应则接受
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: $response_cloudflare_ip
        
  ## > 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches:
        - "qname $local_domain"
        exec: $lazy_cache
      - exec: $query_is_local_domain
      - exec: $has_resp_sequence
      - exec: jump has_resp_sequence
      - exec: $forward_remote

  # 启动 udp 服务器
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"
  # 启动 tcp 服务器。
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
