log:
  level: info
  file: "/tmp/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"
include: []
plugins:

  ## > 外部资源
  # GeoSite gfw规则 + OpenWrt luci 网页 灰名单 规则
  - tag: gfw_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_gfw.txt"
        - "/etc/mosdns/rule/greylist.txt"
  # GeoSite direct规则 
  - tag: direct_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/var/mosdns/geosite_tld-cn.txt"
        - "/var/mosdns/geosite_category-games@cn.txt"
        - "/var/mosdns/geosite_apple.txt"
        - "/var/mosdns/geosite_samsung.txt"
        - "/var/mosdns/geosite_microsoft@cn.txt"
        - "/var/mosdns/geosite_icloud.txt"
        - "/var/mosdns/geosite_ookla-speedtest.txt"
        - "/etc/mosdns/rule/whitelist.txt"
        - "/etc/mosdns/rule/ddnslist.txt"
  - tag: direct_domain6
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_bilibili.txt"

  # cloudflare_cidr规则
  - tag: cloudflare_cidr
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/cloudflare-cidr.txt"
  # 国内ip
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  ## > 缓存设置
  - tag: lazy_cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 259200
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  ## > 转发和解析设置
  - tag: resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept
  # 修改ttl，并终止有应答的响应
  - tag: modify_resp
    type: sequence
    args:
      - exec: ttl 3-5
      - exec: $resp_sequence
  # 丢弃所有V4响应
  - tag: drop_v4_resp
    type: sequence
    args:
      - matches: "resp_ip 0.0.0.0/0"
        exec: reject
      - exec: $modify_resp

  # 转发到openclash
  - tag: forward_openclash
    type: sequence
    args:
      - exec: forward 127.0.0.1:7874
    # 转发到国内DNS服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: ali_doh3      
          addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          idle_timeout: 30
          enable_http3: true
          enable_pipeline: false
        - tag: dnspod_dot
          addr: "tls://1.12.12.12:853"
          idle_timeout: 10
          enable_pipeline: true
      
  # 对gfw域名进行解析
  - tag: query_is_gfw_domain
    type: sequence
    args:
      - matches: "qname $gfw_domain"
        exec: $forward_openclash
  # 对国内域名进行解析
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: "qname $direct_domain"
        exec: $forward_local
  # 对国内域名进行纯V6解析
  - tag: query_is_local_domain6
    type: sequence
    args:
      - matches: "qname $direct_domain6"
        exec: $forward_local

  # fallback 用本地服务器 sequence
  # 返回非国内 ip 则 drop_resp
  - tag: query_is_local_ip
    type: sequence
    args:
      - exec: $forward_local
      - exec: ttl 3-5
      - matches: "resp_ip $cloudflare_cidr"
        exec: black_hole 104.26.9.95 2606:4700:e1:0:22:4702:b817:82fc # 请修改为自选 IP
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp
  # fallback 用远程服务器 sequence
  - tag: query_is_remote
    type: sequence
    args:
      - exec: $forward_openclash
  # fallback 用远程服务器 sequence
  - tag: fallback
    type: fallback
    args:
      primary: query_is_local_ip
      secondary: query_is_remote
      threshold: 500
      always_standby: true

  ## > 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches:
        - "qname $direct_domain | $direct_domain6"
        exec: $lazy_cache
      - exec: $query_is_gfw_domain
      - exec: jump resp_sequence
      - exec: $query_is_local_domain6
      - exec: jump drop_v4_resp
      - exec: $query_is_local_domain
      - exec: jump modify_resp
      - exec: $fallback

  # 启动 udp 服务器
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"
