log:
  level: info
  file: "/tmp/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"
include: []
plugins:

  ## > 外部资源
  # GeoSite gfw规则 + OpenWrt luci 网页 灰名单 规则
  - tag: gfw_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_gfw.txt"
        - "/etc/mosdns/rule/greylist.txt"
  # GeoSite direct规则 + OpenWrt luci网页 白名单 规则
  - tag: direct_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/var/mosdns/geosite_tld-cn.txt"
        - "/var/mosdns/geosite_category-games@cn.txt"
        - "/var/mosdns/geosite_apple-cn.txt"
        - "/var/mosdns/geosite_icloud.txt"
        - "/var/mosdns/geosite_microsoft@cn.txt"
        - "/etc/mosdns/rule/whitelist.txt"
  # cloudflare_cidr规则
  - tag: cloudflare_cidr
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/cloudflare-cidr.txt"
  # 国内ip
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  ## > 缓存设置
  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  ## > 解析判断逻辑
  # 修改ttl并终止响应
  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept
  # 优选cloudflare_cidr
  - tag: modify_cf
    type: sequence
    args:
      - exec: black_hole 104.20.19.35 2a06:98c1:3121:2080:6267:8f60:7135:c1f7 # 请修改为自选 IP
      - exec: $modify_ttl
  # ip属性判断
  - tag: query_modify
    type: sequence
    args:
      - matches: "resp_ip $cloudflare_cidr"
        exec: $modify_cf
      - matches: "qname $direct_domain"
        exec: $modify_ttl
      - matches: "!resp_ip $geoip_cn"
        exec: return

  ## > 转发和解析设置
  # 转发到openclash
  - tag: forward_openclash
    type: sequence
    args:
      - exec: forward 192.168.10.2:7874
  # 对gfw域名进行解析
  - tag: query_is_gfw_domain
    type: sequence
    args:
      - matches: "qname $gfw_domain"
        exec: $forward_openclash
      - matches: has_resp
        exec: accept

  # 转发到国内DNS服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: tls://223.5.5.5:853
        - addr: tls://1.12.12.12:853
          enable_pipeline: true
  # 进行国内DNS解析后判断ip属性
  - tag: direct_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: has_resp
        exec: $query_modify

  ## > 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches:
        - "qname $direct_domain"
        exec: $lazy_cache
      - exec: $query_is_gfw_domain
      - exec: $direct_sequence
      - exec: $forward_openclash

  # 启动 udp 服务器
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"
